FROM golang:1.25.12-alpine3.23@sha256:cc985ef6f9c3bf9ece7488129c9abe0a150388ccdfa428d886fc709dca0b230a
ARG VERSION=not_versioned
ARG CYCLONEDX_GOLANG_VERSION=v1.9.0
RUN mkdir /app && mkdir /sbom
COPY . /app/
WORKDIR /app
RUN go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@${CYCLONEDX_GOLANG_VERSION} \
    && cyclonedx-gomod version \
    && cyclonedx-gomod mod -type library -json -output bom.json . \
    && cp /app/bom.json /sbom/sbom.json
