FROM golang:1.25.11-alpine3.23@sha256:60e626bbde32def8694687d03536ea4341b19e5f068e9a630225a1dfbd0505c9
ARG VERSION=not_versioned
ARG CYCLONEDX_GOLANG_VERSION=v1.9.0
RUN mkdir /app && mkdir /sbom
COPY . /app/
WORKDIR /app
RUN go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@${CYCLONEDX_GOLANG_VERSION} \
    && cyclonedx-gomod version \
    && cyclonedx-gomod mod -type library -json -output bom.json . \
    && cp /app/bom.json /sbom/sbom.json
