FROM golang:1.25.8-alpine3.23@sha256:8e02eb337d9e0ea459e041f1ee5eece41cbb61f1d83e7d883a3e2fb4862063fa
ARG VERSION=not_versioned
ARG CYCLONEDX_GOLANG_VERSION=v1.9.0
RUN mkdir /app && mkdir /sbom
COPY . /app/
WORKDIR /app
RUN go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@${CYCLONEDX_GOLANG_VERSION} \
    && cyclonedx-gomod version \
    && cyclonedx-gomod mod -type library -json -output bom.json . \
    && cp /app/bom.json /sbom/sbom.json
